[tool.black]

line-length = 79

[tool.mypy]

strict = true

[[tool.mypy.overrides]]

module = [
    "pretend",
]

ignore_missing_imports = true

[tool.isort]

multi_line_output = 3
include_trailing_comma = true
