---

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron:  '0 1 * * *'

jobs:
  build:

    strategy:
      matrix:
        uv-resolution: ['highest', 'lowest-direct']
        # The minimum version should be represented in setup.py.
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Create virtual environment"
        run: |
          pip install --upgrade uv
          uv venv ../.venv

      - name: "Install dependencies"
        run: |
          uv pip install --resolution=${{ matrix.uv-resolution }} --upgrade --editable .[dev]

      - name: "Lint"
        env:
          PATH: "../.venv/bin:$PATH"
        run: |
          mypy .
          ruff check .
          ruff format --check .
          pip-extra-reqs pip_check_reqs
          pip-missing-reqs pip_check_reqs
          pylint pip_check_reqs tests
          pyroma --min=10 .
          pyproject-fmt --check --keep-full-version .
          pyright .
          actionlint

      - name: "Run tests"
        run: |
          pytest -s -vvv --cov-fail-under 100 --cov=pip_check_reqs/ --cov=tests tests/

      - name: "Upload coverage to Codecov"
        # The original maintainer of this project is the one with access to the
        # Codecov token and GitHub settings which will allow us to bump to the
        # v4 action.
        uses: "codecov/codecov-action@v3"
        with:
          fail_ci_if_error: true
